main:
  - name: Home
    url: /
    weight: 1
  - name: Blog
    url: blog/
    weight: 2
  - name: Pricing
    url: pricing/
    weight: 3
  - name: Contact
    url: contact/
    weight: 4
  - name: FAQ
    url: faq/
    weight: 5
footer_left:
  - name: About Us
    url: '#'
  - name: Quick Start
    url: '#'
  - name: Pricing
    url: pricing/
footer_middle:
  - name: Pricing
    url: pricing/
  - name: Platform
    url: '#'
  - name: Features
    url: '#'
footer_right:
  - name: Privacy Policy
    url: privacy-policy/
  - name: Terms & Conditions
    url: terms-conditions/
  - name: FAQ
    url: faq/
